// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipay.proto

package com.ipay.api.grpc;

public interface CreateCustomerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ipay.api.CreateCustomerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phonenumber = 3;</code>
   */
  java.lang.String getPhonenumber();
  /**
   * <code>string phonenumber = 3;</code>
   */
  com.google.protobuf.ByteString
      getPhonenumberBytes();
}
