// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipay.proto

package com.ipay.api.grpc;

public interface CreateCustomerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ipay.api.CreateCustomerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.ipay.api.ServiceGenericReply reply = 1;</code>
   */
  boolean hasReply();
  /**
   * <code>.com.ipay.api.ServiceGenericReply reply = 1;</code>
   */
  com.ipay.api.grpc.ServiceGenericReply getReply();
  /**
   * <code>.com.ipay.api.ServiceGenericReply reply = 1;</code>
   */
  com.ipay.api.grpc.ServiceGenericReplyOrBuilder getReplyOrBuilder();

  /**
   * <code>string customer_id = 2;</code>
   */
  java.lang.String getCustomerId();
  /**
   * <code>string customer_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCustomerIdBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phonenumber = 5;</code>
   */
  java.lang.String getPhonenumber();
  /**
   * <code>string phonenumber = 5;</code>
   */
  com.google.protobuf.ByteString
      getPhonenumberBytes();
}
