// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipay.proto

package com.ipay.api.grpc;

public final class IpayApiProto {
  private IpayApiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ipay_api_CreateCustomerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ipay_api_CreateCustomerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ipay_api_CreateCustomerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ipay_api_CreateCustomerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ipay_api_ServiceError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ipay_api_ServiceError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ipay_api_ServiceGenericReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ipay_api_ServiceGenericReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nipay.proto\022\014com.ipay.api\"I\n\025CreateCust" +
      "omerRequest\022\014\n\004name\030\001 \001(\t\022\r\n\005email\030\002 \001(\t" +
      "\022\023\n\013phonenumber\030\003 \001(\t\"\221\001\n\026CreateCustomer" +
      "Response\0220\n\005reply\030\001 \001(\0132!.com.ipay.api.S" +
      "erviceGenericReply\022\023\n\013customer_id\030\002 \001(\t\022" +
      "\014\n\004name\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\023\n\013phonenum" +
      "ber\030\005 \001(\t\"-\n\014ServiceError\022\014\n\004code\030\001 \001(\t\022" +
      "\017\n\007message\030\002 \001(\t\"R\n\023ServiceGenericReply\022" +
      "\017\n\007success\030\001 \001(\010\022*\n\006errors\030\002 \003(\0132\032.com.i" +
      "pay.api.ServiceError2j\n\013IpayService\022[\n\016C" +
      "reateCustomer\022#.com.ipay.api.CreateCusto" +
      "merRequest\032$.com.ipay.api.CreateCustomer" +
      "ResponseB/\n\021com.ipay.api.grpcB\014IpayApiPr" +
      "otoP\001Z\ngolang/apib\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ipay_api_CreateCustomerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ipay_api_CreateCustomerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ipay_api_CreateCustomerRequest_descriptor,
        new java.lang.String[] { "Name", "Email", "Phonenumber", });
    internal_static_com_ipay_api_CreateCustomerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ipay_api_CreateCustomerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ipay_api_CreateCustomerResponse_descriptor,
        new java.lang.String[] { "Reply", "CustomerId", "Name", "Email", "Phonenumber", });
    internal_static_com_ipay_api_ServiceError_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ipay_api_ServiceError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ipay_api_ServiceError_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_com_ipay_api_ServiceGenericReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ipay_api_ServiceGenericReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ipay_api_ServiceGenericReply_descriptor,
        new java.lang.String[] { "Success", "Errors", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
