// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipay.proto

package com.ipay.api.grpc;

public interface ServiceGenericReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ipay.api.ServiceGenericReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>repeated .com.ipay.api.ServiceError errors = 2;</code>
   */
  java.util.List<com.ipay.api.grpc.ServiceError> 
      getErrorsList();
  /**
   * <code>repeated .com.ipay.api.ServiceError errors = 2;</code>
   */
  com.ipay.api.grpc.ServiceError getErrors(int index);
  /**
   * <code>repeated .com.ipay.api.ServiceError errors = 2;</code>
   */
  int getErrorsCount();
  /**
   * <code>repeated .com.ipay.api.ServiceError errors = 2;</code>
   */
  java.util.List<? extends com.ipay.api.grpc.ServiceErrorOrBuilder> 
      getErrorsOrBuilderList();
  /**
   * <code>repeated .com.ipay.api.ServiceError errors = 2;</code>
   */
  com.ipay.api.grpc.ServiceErrorOrBuilder getErrorsOrBuilder(
      int index);
}
